elfboot-y += bootstrap.o
elfboot-y += a20.o
elfboot-y += bda.o
elfboot-y += bios.o
elfboot-y += copy.o
elfboot-y += e820.o
elfboot-y += edd.o
elfboot-y += printf.o
elfboot-y += ptrace.o
elfboot-y += setup.o
elfboot-y += opmode.o
elfboot-y += video.o

elfboot-$(CONFIG_INTR) += entry.o
elfboot-$(CONFIG_INTR) += idt.o
elfboot-$(CONFIG_INTR) += pic.o

# elfboot-y += acpi.o
# elfboot-y += timestamp.o