elfboot-y += bdev.o
elfboot-y += cdev.o
elfboot-y += elf.o
elfboot-y += main.o
elfboot-y += module.o
elfboot-y += pci.o
elfboot-y += printf.o
elfboot-y += string.o
elfboot-y += symbol.o

elfboot-$(CONFIG_INTR) += interrupt.o